# Generated by Django 6.0 on 2026-01-02 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_favorites_post_likes_post_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='stars',
        ),
    ]
